# Generated by Django 5.2.11 on 2026-02-19 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('nit_document', models.IntegerField(primary_key=True, serialize=False)),
                ('kompany_name', models.CharField(max_length=30)),
                ('contact_name', models.CharField(max_length=35)),
                ('phone', models.CharField(max_length=125)),
                ('address', models.CharField(max_length=75)),
            ],
            options={
                'db_table': 'Providers',
            },
        ),
    ]
