# Generated by Django 5.2.11 on 2026-05-25 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Providers', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providers',
            name='type_doc',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='Users.typesdoc'),
        ),
    ]
