# Generated by Django 5.2.11 on 2026-03-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('id_state', models.AutoField(primary_key=True, serialize=False)),
                ('name_state', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'States',
            },
        ),
    ]
