# Generated by Django 5.2.11 on 2026-02-26 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id_permissions', models.AutoField(primary_key=True, serialize=False)),
                ('Module_permission', models.CharField(max_length=50)),
                ('Action', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Permissions',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='RolPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Roles.permissions')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Roles.roles')),
            ],
            options={
                'db_table': 'Rol_permission',
                'unique_together': {('rol', 'permission')},
            },
        ),
        migrations.AddField(
            model_name='roles',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', through='Roles.RolPermission', to='Roles.permissions'),
        ),
    ]
