# Generated by Django 5.2.11 on 2026-02-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('IdRol', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Roles',
            },
        ),
    ]
