# Generated by Django 5.2.11 on 2026-02-18 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Roles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roles',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='roles',
            old_name='IdRol',
            new_name='idRol',
        ),
        migrations.RenameField(
            model_name='roles',
            old_name='Name',
            new_name='name',
        ),
    ]
