# Generated by Django 5.2.11 on 2026-02-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('Doc_identity', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=40)),
                ('Email', models.CharField(max_length=45)),
                ('Password', models.TextField()),
                ('Phone', models.CharField(max_length=20)),
                ('Adress', models.CharField(max_length=25)),
            ],
        ),
    ]
