# Generated by Django 5.2.11 on 2026-02-26 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typesdoc',
            fields=[
                ('id_doc', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'db_table': 'Types_docs',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('doc_identity', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('password', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(default='sin direccion', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id_rol', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Roles.roles')),
                ('type_doc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Users.typesdoc')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
