# Generated by Django 5.2.11 on 2026-05-25 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typesdoc',
            fields=[
                ('id_doc', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'db_table': 'Types_docs',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('doc_identity', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(default='sin direccion', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id_rol', models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='Roles.roles')),
                ('type_doc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Users.typesdoc')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PasswordResetOTP',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('doc', models.CharField(max_length=30, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=120)),
                ('state', models.BooleanField(default=True)),
                ('city', models.CharField(max_length=100)),
                ('type_doc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Users.typesdoc')),
                ('user', models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users_client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Clients',
            },
        ),
    ]
