# Generated by Django 5.2.11 on 2026-02-18 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roles', '0001_initial'),
        ('Users', '0002_alter_users_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='RoleId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Roles.roles'),
        ),
        migrations.AlterField(
            model_name='users',
            name='Email',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
