# Generated by Django 5.2.11 on 2026-03-05 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roles', '0001_initial'),
        ('Users', '0003_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id_rol',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='Roles.roles'),
        ),
    ]
