# Generated by Django 5.2.11 on 2026-02-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_users_roleid_alter_users_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='RoleId',
            new_name='Id_rol',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Adress',
        ),
        migrations.AddField(
            model_name='users',
            name='Address',
            field=models.CharField(default='sin direccion', max_length=150),
        ),
        migrations.AlterField(
            model_name='users',
            name='Name',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='users',
            name='Phone',
            field=models.CharField(max_length=25),
        ),
    ]
