# Generated by Django 5.2.11 on 2026-02-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_rename_roleid_users_id_rol_remove_users_adress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Is_active',
            field=models.BooleanField(default=True),
        ),
    ]
