# Generated by Django 5.2.11 on 2026-02-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_users_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Email',
            field=models.EmailField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='Name',
            field=models.CharField(max_length=40),
        ),
    ]
