# Generated by Django 5.2.11 on 2026-02-18 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_users_email_alter_users_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Doc_identity',
            new_name='doc_identity',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Id_rol',
            new_name='id_rol',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Is_active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Phone',
            new_name='phone',
        ),
    ]
