# Generated by Django 5.2.11 on 2026-02-26 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categories', '0003_alter_categories_description_alter_categories_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id_color', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
            ],
            options={
                'db_table': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id_size', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
            ],
            options={
                'db_table': 'Sizes',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Categories.categories')),
            ],
            options={
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='products/photos/')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='Products.products')),
            ],
            options={
                'db_table': 'Product_photo',
            },
        ),
        migrations.CreateModel(
            name='VariantProduct',
            fields=[
                ('id_variant', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='Products.colors')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='Products.products')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='Products.sizes')),
            ],
            options={
                'db_table': 'Variant_product',
            },
        ),
        migrations.AddConstraint(
            model_name='products',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='price_greater_than_0', violation_error_code='precio_negativo', violation_error_message='el precio del producto no puede ser negativo'),
        ),
        migrations.AlterUniqueTogether(
            name='variantproduct',
            unique_together={('product', 'size', 'color')},
        ),
    ]
