# Generated by Django 5.2.11 on 2026-03-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0003_alter_categories_description_alter_categories_name'),
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='products',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_price__gte', 0)), name='purchase_price_grater_than_0', violation_error_code='precio negativo', violation_error_message='el precio de compra no puede ser negativo'),
        ),
    ]
