# Generated by Django 5.2.11 on 2026-05-26 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_products_purchase_price_grater_than_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='productphoto',
            name='variant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='variant_photo', to='Products.variantproduct'),
        ),
    ]
