# Generated by Django 5.2.11 on 2026-05-26 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_productphoto_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productphoto',
            name='variant',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_photo', to='Products.variantproduct'),
        ),
    ]
