# Generated by Django 5.2.11 on 2026-05-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_alter_productphoto_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colors',
            name='name',
            field=models.CharField(max_length=75, unique=True),
        ),
        migrations.AlterField(
            model_name='sizes',
            name='name',
            field=models.CharField(max_length=75, unique=True),
        ),
    ]
