# Generated by Django 5.2.11 on 2026-05-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0003_alter_categories_description_alter_categories_name'),
        ('Products', '0005_alter_colors_name_alter_sizes_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='products',
            name='price_greater_than_0',
        ),
        migrations.RemoveConstraint(
            model_name='products',
            name='purchase_price_grater_than_0',
        ),
        migrations.AddConstraint(
            model_name='products',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='price_greater_than_0', violation_error_code='precio_negativo', violation_error_message='el precio del producto no puede ser negativo'),
        ),
        migrations.AddConstraint(
            model_name='products',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_price__gt', 0)), name='purchase_price_grater_than_0', violation_error_code='precio negativo', violation_error_message='el precio de compra no puede ser negativo'),
        ),
    ]
