# Generated by Django 5.2.11 on 2026-05-30 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0003_alter_categories_description_alter_categories_name'),
        ('Products', '0006_remove_products_price_greater_than_0_and_more'),
        ('Purchases', '0006_remove_iva_is_active_alter_purchases_iva'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='products',
            name='price_greater_than_0',
        ),
        migrations.RemoveConstraint(
            model_name='products',
            name='purchase_price_grater_than_0',
        ),
        migrations.AddField(
            model_name='products',
            name='iva',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='iva_product', to='Purchases.iva'),
        ),
        migrations.AddConstraint(
            model_name='products',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='price_greater_than_0', violation_error_code='precio_negativo', violation_error_message='el precio del producto no puede ser negativo'),
        ),
        migrations.AddConstraint(
            model_name='products',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_price__gte', 0)), name='purchase_price_grater_than_0', violation_error_code='precio negativo', violation_error_message='el precio de compra no puede ser negativo'),
        ),
    ]
