# Generated by Django 5.2.11 on 2026-05-24 04:20

import api.Returns.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Changes',
            fields=[
                ('id_change', models.AutoField(primary_key=True, serialize=False)),
                ('change_number', models.CharField(default=api.Returns.models.generar_numero_cambio, max_length=50, unique=True)),
                ('reason_of_change', models.CharField(max_length=200)),
                ('stock_applied', models.BooleanField(default=False)),
                ('return_applied', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Changes',
            },
        ),
        migrations.CreateModel(
            name='ChangesDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ChangesDetail',
            },
        ),
        migrations.CreateModel(
            name='ReturnDetail',
            fields=[
                ('id_detail', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'ReturnsDetail',
            },
        ),
        migrations.CreateModel(
            name='Returns',
            fields=[
                ('id_return', models.AutoField(primary_key=True, serialize=False)),
                ('return_number', models.CharField(default=api.Returns.models.generar_numero_devolucion, editable=False, max_length=50, unique=True)),
                ('return_date', models.DateField(auto_now=True)),
                ('reason', models.CharField(max_length=200)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observations', models.CharField(blank=True, max_length=300, null=True)),
                ('balance_in_favor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('difference_to_pay', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Returns',
            },
        ),
    ]
