# Generated by Django 5.2.11 on 2026-05-25 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_products_purchase_price_grater_than_0'),
        ('Returns', '0001_initial'),
        ('Sales', '0001_initial'),
        ('States', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='changes',
            name='sale',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='Sales.sales'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='changes',
            name='state',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='change_state', to='States.states'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='changesdetails',
            name='change',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='change_detail', to='Returns.changes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='changesdetails',
            name='variant_delivered',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='returned_variant', to='Products.variantproduct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='changesdetails',
            name='variant_returned',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='variant_recieved', to='Products.variantproduct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returndetail',
            name='return_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='return_detail', to='Returns.returns'),
        ),
        migrations.AddField(
            model_name='returndetail',
            name='variant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='return_details', to='Products.variantproduct'),
        ),
        migrations.AddField(
            model_name='returns',
            name='sale',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='return_sale', to='Sales.sales'),
        ),
        migrations.AddField(
            model_name='returns',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='return_state', to='States.states'),
        ),
        migrations.AddConstraint(
            model_name='returndetail',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='quantity_greate_than_zero', violation_error_code='cantidad_invalida', violation_error_message='la cantidad tiene que ser mayor a 0'),
        ),
    ]
