# Generated by Django 5.2.11 on 2026-06-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Returns', '0002_changes_sale_changes_state_changesdetails_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returns',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
