# Generated by Django 5.2.11 on 2026-05-25 13:18

import api.Sales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id_sale', models.AutoField(primary_key=True, serialize=False)),
                ('number_sale', models.CharField(default=api.Sales.models.generate_number, editable=False, max_length=50, unique=True)),
                ('date_sale', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('output_executing', models.BooleanField(default=False)),
                ('return_executing', models.BooleanField(default=False)),
                ('void', models.BooleanField(default=False)),
                ('void_reason', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Sales',
            },
        ),
        migrations.CreateModel(
            name='SalesDetail',
            fields=[
                ('id_detail', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'SalesDetail',
            },
        ),
    ]
