# Generated by Django 5.2.11 on 2026-05-05 01:35

import api.Sales.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clients', '0001_initial'),
        ('Orders', '0001_initial'),
        ('Products', '0002_products_purchase_price_grater_than_0'),
        ('States', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id_sale', models.AutoField(primary_key=True, serialize=False)),
                ('number_sale', models.CharField(default=api.Sales.models.generate_number, editable=False, max_length=50, unique=True)),
                ('date_sale', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('output_executing', models.BooleanField(default=False)),
                ('return_executing', models.BooleanField(default=False)),
                ('void', models.BooleanField(default=False)),
                ('void_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='Clients.clients')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='Orders.paymentmethods')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='States.states')),
            ],
            options={
                'db_table': 'Sales',
            },
        ),
        migrations.CreateModel(
            name='SalesDetail',
            fields=[
                ('id_detail', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_detail', to='Sales.sales')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_details', to='Products.variantproduct')),
            ],
            options={
                'db_table': 'SalesDetail',
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='quantity_gt_cero', violation_error_code='quantity invalid', violation_error_message='la cantidad no puede ser menor o 0')],
            },
        ),
    ]
