# Generated by Django 5.2.11 on 2026-05-25 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Orders', '0002_orders_client_orders_payment_method_orders_state_and_more'),
        ('Products', '0002_products_purchase_price_grater_than_0'),
        ('Sales', '0001_initial'),
        ('States', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='Users.clients'),
        ),
        migrations.AddField(
            model_name='sales',
            name='payment_method',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='Orders.paymentmethods'),
        ),
        migrations.AddField(
            model_name='sales',
            name='state',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='States.states'),
        ),
        migrations.AddField(
            model_name='salesdetail',
            name='sale',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sale_detail', to='Sales.sales'),
        ),
        migrations.AddField(
            model_name='salesdetail',
            name='variant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sales_details', to='Products.variantproduct'),
        ),
        migrations.AddConstraint(
            model_name='salesdetail',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='quantity_gt_cero', violation_error_code='quantity invalid', violation_error_message='la cantidad no puede ser menor o 0'),
        ),
    ]
