# Generated by Django 5.2.11 on 2026-06-03 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_orders_user'),
        ('Sales', '0003_sales_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='order_sale', to='Orders.orders'),
        ),
    ]
