# Generated by Django 5.2.11 on 2026-06-04 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_orders_user'),
        ('Sales', '0004_sales_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='order',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_sale', to='Orders.orders'),
        ),
    ]
