# Generated by Django 5.2.11 on 2026-06-17 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_alter_orders_payment_method_alter_orders_state_and_more'),
        ('Products', '0007_remove_products_price_greater_than_0_and_more'),
        ('Sales', '0005_alter_sales_order'),
        ('States', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_sale', to='Orders.orders'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='Orders.paymentmethods'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='States.states'),
        ),
        migrations.AlterField(
            model_name='salesdetail',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_detail', to='Sales.sales'),
        ),
        migrations.AlterField(
            model_name='salesdetail',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_details', to='Products.variantproduct'),
        ),
    ]
