# Generated by Django 5.2.11 on 2026-06-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0006_alter_sales_order_alter_sales_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
