# Generated by Django 5.2.11 on 2026-05-24 04:20

import api.Orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('number_order', models.CharField(default=api.Orders.models.generate_number_order, editable=False, max_length=50, unique=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('address_shipment', models.CharField(max_length=200)),
                ('person_receives', models.CharField(max_length=100)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observations', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrdersDetail',
            fields=[
                ('id_detail', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('sales_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'db_table': 'Orders_detail',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id_method', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Payment_Methods',
            },
        ),
    ]
