<<<<<<< HEAD
# Generated by Django 5.2.11 on 2026-05-05 01:35

import api.Orders.models
import django.db.models.deletion
=======
# Generated by Django 5.2.11 on 2026-05-24 04:20

import api.Orders.models
>>>>>>> juanjo
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('Clients', '0001_initial'),
        ('Products', '0002_products_purchase_price_grater_than_0'),
        ('States', '0001_initial'),
=======
>>>>>>> juanjo
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='PaymentMethods',
            fields=[
                ('id_method', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Payment_Methods',
            },
        ),
        migrations.CreateModel(
=======
>>>>>>> juanjo
            name='Orders',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('number_order', models.CharField(default=api.Orders.models.generate_number_order, editable=False, max_length=50, unique=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('address_shipment', models.CharField(max_length=200)),
                ('person_receives', models.CharField(max_length=100)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observations', models.CharField(blank=True, max_length=300, null=True)),
<<<<<<< HEAD
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.clients')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='States.states')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Orders.paymentmethods')),
=======
>>>>>>> juanjo
            ],
            options={
                'db_table': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrdersDetail',
            fields=[
                ('id_detail', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('sales_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
<<<<<<< HEAD
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_order', to='Orders.orders')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details_order', to='Products.variantproduct')),
            ],
            options={
                'db_table': 'Orders_detail',
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='quantity_greather_than', violation_error_code='quantity_invalid', violation_error_message='la cantidad no puede ser menor o igual a 0')],
=======
            ],
            options={
                'db_table': 'Orders_detail',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id_method', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Payment_Methods',
>>>>>>> juanjo
            },
        ),
    ]
