# Generated by Django 5.2.11 on 2026-05-25 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
        ('Products', '0002_products_purchase_price_grater_than_0'),
        ('States', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.clients'),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Orders.paymentmethods'),
        ),
        migrations.AddField(
            model_name='orders',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='States.states'),
        ),
        migrations.AddField(
            model_name='ordersdetail',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='detail_order', to='Orders.orders'),
        ),
        migrations.AddField(
            model_name='ordersdetail',
            name='variant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='details_order', to='Products.variantproduct'),
        ),
        migrations.AddConstraint(
            model_name='ordersdetail',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='quantity_greather_than', violation_error_code='quantity_invalid', violation_error_message='la cantidad no puede ser menor o igual a 0'),
        ),
    ]
