# Generated by Django 5.2.11 on 2026-06-17 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_orders_user'),
        ('Products', '0007_remove_products_price_greater_than_0_and_more'),
        ('States', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Orders.paymentmethods'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='States.states'),
        ),
        migrations.AlterField(
            model_name='ordersdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_order', to='Orders.orders'),
        ),
        migrations.AlterField(
            model_name='ordersdetail',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details_order', to='Products.variantproduct'),
        ),
    ]
