<<<<<<< HEAD
# Generated by Django 5.2.11 on 2026-03-09 12:06
=======
# Generated by Django 5.2.11 on 2026-05-24 04:20
>>>>>>> juanjo

import api.Purchases.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('Products', '0001_initial'),
=======
        ('Products', '0002_products_purchase_price_grater_than_0'),
>>>>>>> juanjo
        ('Providers', '0001_initial'),
        ('States', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id_purchase', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_number', models.CharField(default=api.Purchases.models.generar_numero_compra, editable=False, max_length=50, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('registration_date', models.DateField(auto_now=True)),
                ('observations', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='Providers.providers')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='States.states')),
            ],
            options={
                'db_table': 'Purchases',
            },
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('id_detail', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sales_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
<<<<<<< HEAD
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='Products.variantproduct')),
=======
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases_details', to='Products.variantproduct')),
>>>>>>> juanjo
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_purchase', to='Purchases.purchases')),
            ],
            options={
                'db_table': 'Purchase_detail',
<<<<<<< HEAD
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='quantity_gte_0', violation_error_code='quantity_invalid', violation_error_message='la cantidad no puede ser menor o igual a 0')],
=======
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='quantity_gt_0', violation_error_code='quantity_invalid', violation_error_message='la cantidad no puede ser menor o igual a 0')],
>>>>>>> juanjo
            },
        ),
    ]
