# Generated by Django 5.2.11 on 2026-05-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='state',
        ),
        migrations.AddField(
            model_name='purchases',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
