# Generated by Django 5.2.11 on 2026-05-05 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_products_purchase_price_grater_than_0'),
        ('Purchases', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveConstraint(
        #     model_name='purchasedetail',
        #     name='quantity_gte_0',
        # ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases_details', to='Products.variantproduct'),
        ),
        # migrations.AddConstraint(
        #     model_name='purchasedetail',
        #     constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='quantity_gt_0', violation_error_code='quantity_invalid', violation_error_message='la cantidad no puede ser menor o igual a 0'),
        # ),
    ]
