# Generated by Django 5.2.11 on 2026-05-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchases', '0002_remove_purchases_state_purchases_canceled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Iva',
            },
        ),
    ]
