# Generated by Django 5.2.11 on 2026-05-27 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchases', '0004_alter_purchases_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='iva',
            field=models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.PROTECT, related_name='iva_purchase', to='Purchases.iva'),
        ),
    ]
