# Generated by Django 5.2.11 on 2026-05-28 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchases', '0005_alter_purchases_iva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iva',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='purchases',
            name='iva',
            field=models.ForeignKey(db_column='iva_id', on_delete=django.db.models.deletion.PROTECT, related_name='iva_purchase', to='Purchases.iva'),
        ),
    ]
