# Generated by Django 5.2.11 on 2026-06-02 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Purchases', '0006_remove_iva_is_active_alter_purchases_iva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='iva',
        ),
    ]
