# Generated by Django 5.2.11 on 2026-06-16 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Purchases', '0002_remove_purchasedetail_quantity_gte_0_and_more'),
        ('Purchases', '0007_remove_purchases_iva'),
    ]

    operations = [
    ]
