# Generated by Django 5.2.11 on 2026-03-03 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('doc', models.CharField(max_length=30, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=120)),
                ('state', models.BooleanField(default=True)),
                ('city', models.CharField(max_length=100)),
                ('type_doc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Users.typesdoc')),
            ],
            options={
                'db_table': 'Clients',
            },
        ),
    ]
