# Generated by Django 5.2.11 on 2026-02-26 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id_inventory', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Products.variantproduct')),
            ],
            options={
                'db_table': 'Inventory',
                'constraints': [models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='stock_greater_than_0', violation_error_code='invalid_stock', violation_error_message='el stock no puede ser menor a 0')],
            },
        ),
    ]
